import axios from 'axios';
import fs from 'fs';
import path from 'path';

// Hardcoded nested iframe URL from previous step
const targetUrl = 'https://cloudnestra.com/prorcp/ZTNlNWRmNGRiODVmMTI3Y2I0MjgzZDJmNTJhY2E4ZjY6T0ZoeU0xZFhjSFIyVFhCVmJqTnNNRzR3TUZneU5YbHlVVEF5TVdJMlJtdEZTRkJLVnpVeVNXcFZTM3AzV2s1bFpUTnFLMFJFV1N0amRFZExibE5TVjFGUmNqRkphVGR1UldGWmJFZ3dkRWRvSzBreWFuUXdMMG8yZDNGdU1Ga3dablIwVnpOTVdIVTBlWEpPY0VGTlkyZzNaRkIzZFV0RVpIRnViVGxLUkVGQ1ZsZHRjbkJ1U21KTU4xcFpaVFJ0Vmk5cEt5OXlTVmRoU3psUWVFZ3ZhV05yUzJaaldHTTJaamw1WXk5U09XOWlWekJrYW1aM2ExZEVaM0pMVkVaRWF6UkVhMkpZZGtGbWMxaG9VR0ZPYURGVmFuazBaVUpFZG1GTlNVTkxkVTV4T1VreWF6WlVZVFJ2YW5oMVkxaENaV05XVUVGcWFrRjRiVkJRZUdOcFdHczRUMDlFVjNGMVZEaDVia0pPVWpJdk16ZHdNV3hvZFRKaGJVbHdWMnB6VDNCdFdGcFJTMnhQVEdSR09VSlVMMU5RTHpOcFZGWktjbVZMYW1RMmRtVnVSbEE1Umk5MFJUTlBibEJpYlVkdmQyWXZWVGRsTldJM1dUZEdZbTVyU0M5VEx6UjJWemg1WlZsTGN6a3dPR2hCZVRsWUwxbE5ZMGMzZVRWNU1uQmlkVk5oTXpCSFoxaGlUVmxWTUdKS1VrYzBZMHhWVDNwRWJHSnZUVFJGT0VSeFRYZHVhbk53ZW10V1JFWnFNWGxOYW5oSGEyVklSa0YwTWpGa2NFWlJLMmhCWmpkSldGYzFSVUptVGt3ck5pc3daQ3MxVjI1RVRVZHZNUzlNVWpVMmNXbG5ZMDFGUnpSR01FcGljWEppTkZkSE1WRnJWbWx1VUd4a1pEQk1ZMlpKYmpGUGQzVk1ReTlIVXpGbVZuZEVWMUUzZHpNNWNsVmFhbmcyUkVoTlFreDBkbmhYVWtZMlJrcEdjMk5pYkhSUk1YcFBVakZUTnpOVFpHRjRlalZMVmtsTEsyNDFNWFpwVGprNFMwWTVjVWR4VVZoWlIwRlZUWEJLTmtneVkweE9iVVpKZUhrMFJGZDRSblFyTVVscmFuTnFXRkUyUm1sNlVVTXlkVVZFZDFBMk9EaGpPSGRyWXpFM2N6bGtWMEpvUTNCaWR6TmxTV2hRWmtoUFRqQjBaRmx1U2pWSE9FSXZZbGh5Y2pkVE1GQjBRVEJMYWxseU1YbE9VUzlDVEdKa00wZ3hkR294T1hkTFp6WmtaMlpvVFVWaFl6WkZaVVZaUzFoSk4xSm1ZazVSY2pCTWNUa3ZRVmROTlRkT1pGQlVkMGN5Y1ROQ2JWSk1TVGQxU0d4cGJTOTFZMVZOV0V4VU1GVTJhazFzVDIxcU1Vb3JkbUpHVlhOclYyVm9ialZSU1hKa1EyUnNiWFJYZFZacVYyeFJZaTh3UjA5M1dGVnBWMnQ0VHprMGVHcDFTRTVSWlZBMWEwWXliekppVVhwUVYwTmljRk4wVFU1UksyeDFjRWhhYmpOR1RXdHVSV1pGTHpOTk0wdHpNSEk0Y2pBeVMyZ3JObG95VkZoQldEVm1jazVzYzJsTWNVWkRjSGxKWjBSWmJEUXJSRTltYlM5Nk4wZ3hWRTFzYW1zeGJISnBVMHBLVlhsWWQwazVjbWhGWWtGU1drazRNWGh6RkZLUzNWRGFIRlhSVXczZFdkV1dtUkVVV2RSTXpWUVVUZFJUVzQ1UTFkTE9VUlNaVXRoTVhWUldsSlZUVFp1YkRaaVNXUmljVFp0VFRGUldUTXlWbEJNYkc5NVoyTTVSMnBRYUhkck5XMDJSWGw1ZDNocE5ISkZSbVZWWmtGbE0wdGlZMFJSZVdoTFMxWjBOM2QxVFRGT0wybERla2N3V21KelIxZG1NQzlRUTIwM1dVUTFabXRpTlZSbFdtdHZXR3BDVTFaelZFVXhkV2RyUTAxdUt6WXdkbFZ4UVhsalRFeEZWVlZPTTIwM1puWXhWVUp5UWtaTloweHJlbW94VUdWSFlUTkRUbW94VDNKVlQwRjViM0ZPT1VSRVFuUklkWFJTV1ZwQlVtVXJhaTlXT1hWUFRGUnpkMDF2WjNaelVWVTFNMk5FVjNCUFZtdHlaVlpoTldablJFRXZabnBrZERkSldITm5TRlIxY25WS1F6RkxWazV2YlZWUE5VRmxSRU5YZW1OWVREZFBRazB6VVdZM2NrWnJhWGhNWmpCSk0wWkxTVTlKYkc5bGIzaEZUV3BWVEU5eVpETTBSRkV2T1hCVmNrSmhhRmxpVTFkVmJtNWliemxTYW5CTGRrVTFRVEJCVFdoa1lXWk1XRVJJYlRsUWRIcGxPV1JVWm1VMlRqWjZaV2RXT0dKdGRsQndXVGRHTUU5eldFWnVLMWxXZDJOeFkzSkNWVVJXTlUxSWQydFhkblZWYUhGYVMxTnlXbUpZTVRoWll5dHVTbE41YzNoaWRtOUpiVkp1YkZaMldEQjZLemN5Vm5GRE9VWnFOVXRPYTJKVlRHcHVaRnBEUjNwd2VIRnJhekVyY21sbmMweHVhM0p4YVZoSlZ6QjNkVkJ6YldveE9ETkRiMDFGUm1vd2VYRXZSV0k0U0RkRFRETk9NVkZLYVRsVWMzaGhZM1ZYZGxjM00xQnFVR05OVG1aV05EQktXbEptYkhwUFpFTllWbFZNYmtjM2JUZ3JWRkl6V0hWblJuSk9NV1pVT0VoR1NrWjNOVWxsZWpoRGJsZzRWbEkzT1RSS1QwdGhSM1ZWYjFvcldWcDZOMmhZTkRkR05qbHVhR3RuWm5RclpFdFlOVlZTVTI4NVJVMUpjMlpMYVV0RVVuQmhNSEZSV2pCelIwaHFWSEpYZEVkeFprNU5VRTVxVGxrMk9WbFlhR2xWVDA0MFUxZFFVVUYzTjJONlIyaDNkMDB6VjFCR1JFTkROM0UwTWxFNGNtaElja2hOTHpKaFlrWTBUWHAxVVVOa2FtZHljMUYyWWtsd1JqWlVSelpoUm1ObFUzSnRORXh6WkdOSVNEbFVRMklyVG1kdlQxTlFWRGhRTldkSmNrRkJVMGxGVEM4NWNsQmhhU3MwU1hocVMyOTJiRE5FYUdGV1pGRk9ZbmRRU0ZaUlFsVTVMMGRKYWpjeU0zbElibmxDVjBsRU4xWlVWVnB5U2tSdk0ySTBiRE0yUjFwaVpUZEZXRnBqZVZaWVNWRndSbGxNUkVRMlVWVXZPVVpUUkU5VE0xVllWVWd2WkZwTVUyUm1TM05MVEVoU1RVSm1XRlpVYzFwNFluUk1LMWRPYzJzMk5WSkdjV005';
console.log(`[Source] Fetching: ${targetUrl.substring(0, 50)}...`);

async function run() {
    try {
        const response = await axios.get(targetUrl, {
            headers: {
                'Referer': 'https://vidsrc-embed.ru/',
                'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
            }
        });

        console.log('[Source] Status:', response.status);
        fs.writeFileSync('source_dump.html', response.data);
        console.log('[Source] Saved to source_dump.html');

        // Quick scan
        if (response.data.includes('vtt') || response.data.includes('srt')) {
            console.log('[Source] 🚨 Found VTT/SRT references in source!');
        }
        if (response.data.includes('tracks')) {
            console.log('[Source] 🚨 Found "tracks" keyword in source!');
        }

    } catch (e) {
        console.error('[Source] Error:', e.message);
    }
}

run();
